# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e27fee646caee330054e713fe5e824051dc6ffa82498bea4024ab33c3eda33ce7435cdd5deae09164b7d7a17a0f68d88cfa0f3a35ba89ab95730ea670cf3552f

test:
  secret_key_base: 802d2656b12ab7df4d11cee4b277c5f502ae65ca350f4886df8fc47d2c2b1c85767da57346851d4f5ec1208d0e1eca5df668219965768a4057936ebd5b68c24e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
